### ISSUE TITLE
cannot interpret I32(None) as an u8 value

### ISSUE THREAD

**Issue by dylan-bowker** [prisma/tiberius#119]
I have a struct where the last field (15th field) is an `Option<u8>` (confirmed correct). In the database, the corresponding column is a `tinyint NULL` (confirmed correct)

When I start streaming data from the SQL server I receive this error: `Conversion error: cannot interpret I32(None) as an u8 value`

For testing outside of a struct, if I put this code in: `println!("{:?}", row.get::<u8, _>(15));` I receive the error `Conversion error: cannot interpret I32(None) as an u8 value` on the very first row,  which has a value of `null` for the 15th column.

If I change the above code to an i32: `println!("{:?}", row.get::<i32, _>(15));` the first row with the `None` now works. However, I receive the error `Conversion error: cannot interpret U8(Some(1)) as i32 value` when it encounters the first `Some()` value in the stream.

Haha. I think Tiberius is confused?? The server is MSSQL 2012. The column really is a `u8` both in the struct and in the database.

```
  14: tiberius::row::Row::get<u8,usize><unknown>
      at C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\tiberius-0.5.5\src\row.rs:369
```

**Comment by pimeys** [comment]
I made a PR (link above this comment) that tests reading and writing tinyints to and from u8. The test is green, so maybe you have something else broken in your code?

**Comment by dylan-bowker** [comment]
It's an intermittent problem. I'm having this same issue with another table too, now. The field is structured as an `Option<i64>` client side, as a `bigint NULL` server side. Tiberius is saying `cannot interpret I32(None) as i64 value`.

How does Tiberius determine that a None is an I32(None) vs an I64(None)? Is that info sent by the server? Maybe that info is not being sent by the server? Is it being sent incorrectly? Should a NULL be typed?

**Comment by SpeedSX** [comment]
This is very similar to the problem I reproduced earlier with U8(None) and nullable int field. See #80 
Now I can see I could implement that much simpler, so created another PR GH-121  where also added a possible fix for the issues mentioned above. Unfortunately I also cannot reproduce the error reported.

**Comment by pimeys** [comment]
Thx for fix. Try out version 0.5.6, that should have a fix.

**Comment by dylan-bowker** [comment]
Amazing! I am off that particular project for the moment but I'll let you know how it looks next week. Wish I could do more to contribute.

**Comment by dylan-bowker** [comment]
Just an update - fix works for ints but not for floats.

**Comment by SpeedSX** [comment]
@dylan-bowker Does error message look similar, like `cannot interpret F32(None) as an u8 value`?

**Comment by dylan-bowker** [comment]
I will get back to you with the exact message
