### ISSUE TITLE
Failed to compile while using feature "integrated-auth-gssapi"

### ISSUE THREAD

**Issue by aanavaneeth** [prisma/tiberius#126]
Hello Team,

The project is failed to compile with below error when I used "integrated-auth-gssapi" feature.
`error: failed to run custom build command for libgssapi-sys v0.2.2`

We have Kerberos MIT distribution. Does it cause this issue?

**Comment by aanavaneeth** [comment]
thread 'main' panicked at 'Unable to find libclang: "the `libclang` shared library at /usr/lib64/clang-private/libclang.so.7 could not be opened: libclangAST.so.7: cannot open shared object file: No such file or directory"', /u/anappind/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.55.1/src/lib.rs:1896:31
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by aanavaneeth** [comment]
Sorry it was an issue with permissions. I could fix the compilation issue

**Comment by pimeys** [comment]
Glad you got it figured out :)
