### ISSUE TITLE
Integration authentication throwing error

### ISSUE THREAD

**Issue by aanavaneeth** [prisma/tiberius#127]
Hello!

I am trying out Tiberius with integrated authentication on RHEL. Connection is failing with below error
```
Error: Token error: ' 'Logon failed for login 'DOMAIN\USERNAME' due to trigger execution.' on server SERVERNAME executing  on line 1 (code: 17892, state: 1, class: 14)
```
Could someone help?

**Comment by aanavaneeth** [comment]
I am able to debug this. This is not an authentication issue. but there is a logon trigger that's rejecting the request. And the reason was that "program name" is empty when connecting through tiberius driver. Is there a way to set program name?

**Comment by pimeys** [comment]
Are you using the latest version? We're at least setting the app name here: https://github.com/prisma/tiberius/blob/master/src/tds/codec/login.rs#L165

**Comment by aanavaneeth** [comment]
yes I am using the latest version. Does it add app_name for integration authentication as well?

**Comment by pimeys** [comment]
Yeah, that's for all LOGIN7 packages. I have no experience at all from the kerberos systems, but you might also want to take a look how the integrated authentication is written here:

https://github.com/prisma/tiberius/blob/master/src/client/connection.rs#L277-L316

Maybe we miss some parameter there? Maybe the author of this change, @dwink, could help here?

**Comment by aanavaneeth** [comment]
If @dwink can help, that would be awesome!
I just a beginner with Rust. I am little under-confident to make code change and submit PR, But, I will also try it.

**Comment by pimeys** [comment]
If you can get something to work, anything, please provide a PR and we can make it pretty afterwards.

**Comment by pimeys** [comment]
You can also from your application point to your local copy of `tiberius` by instead of providing a `version` in your Cargo.toml, set a `path="/path/to/tiberius"`. This makes it easier for you to iterate on changes to see if you can get the authentication to work.

**Comment by dwink** [comment]
> I am able to debug this. This is not an authentication issue. but there is a logon trigger that's rejecting the request. And the reason was that "program name" is empty when connecting through tiberius driver. Is there a way to set program name?

Any chance you have access to the code for that login trigger, so we can get the precise field it’s looking for?

**Comment by pimeys** [comment]
Interesting... I can't find anything about program name from the TDS manual. Should it be in the LOGIN7?

**Comment by dwink** [comment]
> Interesting... I can't find anything about program name from the TDS manual. Should it be in the LOGIN7?

I think it’s a synonym for APP_NAME, perhaps from older SQL Server versions. One way to troubleshoot would be to put a known-working value in (instead of “tiberius”) — perhaps the trigger only allows certain values for the program name, but gives a misleading message. (Like, maybe the SQL joins to a table of known apps).

**Comment by dwink** [comment]
Wait — @aanavaneeth , you said you were using 0.5.8? That one sets the app_name to “”.

https://github.com/prisma/tiberius/blob/923bcbf1419d414de62f8da1631a1f8efbed7401/src/tds/codec/login.rs#L148

Can you try with the master branch?

**Comment by pimeys** [comment]
Oh damn, I forgot that I didn't release this change! I was just thinking it's a refactor, we'll release it with some actual features. But I anyhow saw the app name being empty and decided to add "tiberius" to it, because why not... Good catch!

**Comment by dwink** [comment]
> Oh damn, I forgot that I didn't release this change! I was just thinking it's a refactor, we'll release it with some actual features. But I anyhow saw the app name being empty and decided to add "tiberius" to it, because why not... Good catch!

Ideally, users of the driver should be able to set this somehow — in ODBC, you pass it in on your connection string, so some DBAs set restrictions on what apps can connect. But that’s a different issue :)

**Comment by pimeys** [comment]
It's easy to add of course. The thing with me and this crate is that I never want to add any public API if I'm not sure about its usefulness. SQL Server has lots of weird stuff I'm learning every day, this is one of those things...

**Comment by dwink** [comment]
> It's easy to add of course. The thing with me and this crate is that I never want to add any public API if I'm not sure about its usefulness. SQL Server has lots of weird stuff I'm learning every day, this is one of those things...

I think that’s a good approach, TBH. Considering its lineage from [Sybase](https://blogs.sap.com/2011/04/15/a-deeper-look-at-sybase-history-of-ase/), there’s 35 years of history all the way back to competing with mainframes & ISAM systems, so there are bound to be a few features that have crept in to SQL Server over time...

**Comment by aanavaneeth** [comment]
@pimeys will you be able to release a new version with app name setting? That helps!

**Comment by pimeys** [comment]
Does the master code work? If it does, I'll cut a release.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by aanavaneeth** [comment]
I have cloned the repo and tried using local master branch and it worked!!

**Comment by pimeys** [comment]
v0.5.9 is out with the patch.
