### ISSUE TITLE
Connect local instance without port

### ISSUE THREAD

**Issue by gaoqiangz** [prisma/tiberius#128]
How to connect local instance without port like `.\[InstanceName]` using **IntegratedSecurity**?

**Comment by aanavaneeth** [comment]
just curious why you don't want to add port number.

**Comment by aanavaneeth** [comment]
@pimeys can we have port number as optional and have 1433 as default?

**Comment by pimeys** [comment]
Looks like the ado.net is defaulting to `1434`, but looks like it should be `1433`. Please send me a PR to change this.

**Comment by gaoqiangz** [comment]
We have many servers with different ports. In order to facilitate the deployment of services, we now use the integrated authentication method without providing a port number. 
We use `odbc-rs` driver to access mssql currently, now I want to change to `tiberius`.
By the way, I have been following this project since tiberius 0.3.x and it looks very good now. Thank you very much for your excellent work! :-) @pimeys

**Comment by pimeys** [comment]
So, summarizing:

Here's a test to show how we do not have to provide a port number in the connection string:
https://github.com/prisma/tiberius/blob/master/src/client/config/ado_net.rs#L102-L113

But what I see here the default is wrong, it should be 1433, not 1434. It would be a great first pull request for one of you to try out to modify the SQL Server code base! :)

**Comment by aanavaneeth** [comment]
can we also have 1433 for JDBC as well as  default port?

**Comment by gaoqiangz** [comment]
> 
> 
> So, summarizing:
> 
> Here's a test to show how we do not have to provide a port number in the connection string:
> https://github.com/prisma/tiberius/blob/master/src/client/config/ado_net.rs#L102-L113
> 
> But what I see here the default is wrong, it should be 1433, not 1434. It would be a great first pull request for one of you to try out to modify the Tiberius code base! :)

I solved this problem by using `SqlBrowser` APIs,the address was changed to `127.0.0.1\[InstanceName]`,and the default port 1434 is correct!
