### ISSUE TITLE
Is there any way to batch the results?

### ISSUE THREAD

**Issue by kesavkolla** [prisma/tiberius#140]
Can we support batch reads of the results? I typically deal with millions of rows from query output. It would be great if there is a way to batch the results so that I can start processing as soon as a batch is available.

**Comment by pimeys** [comment]
Can you point in the TDS specification what this batching means? Could it be handled in the query level or do we need some special TDS parameters to enable that?

**Comment by kesavkolla** [comment]
I'm no expert in TDS protocol but what I see from other implementation like jdbc or turbodbc there is a way to set batch size for results. Especially the turbodbc does convert the batch results into apache arrow batches. This is the feature really gives lot of benefit. There is lots of movemoent towards implementing Apache arrow in data access mechanisms.

I know it's not definetly not in TDS spec to convert the data into arrow batches but would be a great feature addition.

**Comment by pimeys** [comment]
Well, Tiberius gives you a stream, where you get data row by row if you want. You can implement batch easily on top of this if you need...

**Comment by pimeys** [comment]
E.g. using the `StreamExt` you can batch using the `chunks` method. https://docs.rs/futures/0.3.13/futures/stream/trait.StreamExt.html#method.chunks
