### ISSUE TITLE
Is there any connection retry mechanism builtin?

### ISSUE THREAD

**Issue by kesavkolla** [prisma/tiberius#141]
Sometimes we get connection disconnects from SQL Server. Is there any retry mechanism built-in so that client would fail the current operation and reconnects automattically so the next operations woould succeed.

**Comment by pimeys** [comment]
No. And probably will not be. What we do in Prisma is we utilize crates such as mobc to enable health checks and retries. The plan in Tiberius is to be only a good TDS implementation, I'd expect people to build higher level crates on top of this to enable pooling and all that.

**Comment by kesavkolla** [comment]
:-(
