### ISSUE TITLE
Support for Multiple Active Result Sets (MARS)

### ISSUE THREAD

**Issue by kesavkolla** [prisma/tiberius#142]
SQL Server has a spec (https://docs.microsoft.com/en-us/sql/relational-databases/native-client/features/using-multiple-active-result-sets-mars?view=sql-server-ver15) for MARS so that we can execute multiple queries on single connection. Will this feature be supported?

**Comment by pimeys** [comment]
It is supported already...

For example https://github.com/prisma/tiberius/blob/master/tests/query.rs#L483-L507

**Comment by kesavkolla** [comment]
According to MARS the resultsets can be interleaved. How can you write assert statements saying first resultset will be the results of first query? Isn't that random the way the results comeback?

**Comment by pimeys** [comment]
No, they come in order.

**Comment by matthewmueller** [comment]
Does this answer your question @kesavkolla ?
