### ISSUE TITLE
tcp.compat_write() not found in tokio::net::TcpStream

### ISSUE THREAD

**Issue by ArunGust** [prisma/tiberius#145]
Hi,  
I got below error. Any idea ?

34 |             Client::connect(config, tcp.compat_write()).await?
   |                                         ^^^^^^^^^^^^ method not found in `tokio::net::TcpStream`

**Comment by esheppa** [comment]
Hi @ArunGust you probably need to do the following:
* add the below to your Cargo.toml
```
[dependencies.tokio-util]
version = "0.6"
features = ["compat"]
```

* add `use tokio_util::compat::TokioAsyncWriteCompatExt` in your code

**Comment by ArunGust** [comment]
Thanks. I could solve
