### ISSUE TITLE
Connection pooling

### ISSUE THREAD

**Issue by servonlewis** [prisma/tiberius#146]
Hey guys,

Is there any example of how to create an mssql connection pool, rather than initiating a new connection per query?

If so, how can I do it?

**Comment by SpeedSX** [comment]
I'm using **bb8** for that, see https://github.com/SpeedSX/consum-api/blob/master/src/connection_manager.rs

**Comment by servonlewis** [comment]
> I'm using **bb8** for that, see https://github.com/SpeedSX/consum-api/blob/master/src/connection_manager.rs

This is the code i used to do it with Tiberius and async-graphql for those who care.

```rust
//db.rs
use async_trait::async_trait;
use bb8::Pool;
use tiberius::{error::Error, AuthMethod, Client, Config};
use tokio::net::TcpStream;
use tokio_util::compat::{Compat, TokioAsyncWriteCompatExt};

#[derive(Clone, Debug)]
pub struct TiberiusConnectionManager {
    config: Config,
}

impl TiberiusConnectionManager {
    /// Create a new `TiberiusConnectionManager`.
    pub fn new(config: Config) -> tiberius::Result<TiberiusConnectionManager> {
        Ok(TiberiusConnectionManager { config })
    }
}

#[async_trait]
impl bb8::ManageConnection for TiberiusConnectionManager {
    type Connection = Client<Compat<TcpStream>>;
    type Error = Error;

    async fn connect(&self) -> Result<Self::Connection, Self::Error> {
        let tcp = TcpStream::connect(&self.config.get_addr()).await?;
        tcp.set_nodelay(true)?;

        Client::connect(self.config.clone(), tcp.compat_write()).await
    }

    async fn is_valid(
        &self,
        conn: &mut bb8::PooledConnection<'_, Self>,
    ) -> Result<(), Self::Error> {
        //debug!("Checking {:?}", conn);
        conn.simple_query("").await?.into_row().await?;
        Ok(())
    }

    fn has_broken(&self, _: &mut Self::Connection) -> bool {
        false
    }
}

pub async fn create_connection(
    host: &str,
    database: &str,
) -> anyhow::Result<Pool<TiberiusConnectionManager>> {
    let mut config = Config::new();
    config.host(host);
    config.database(database);
    config.authentication(AuthMethod::Integrated);
    config.trust_cert();
    let manager = TiberiusConnectionManager::new(config).unwrap();
    let pool = bb8::Pool::builder().build(manager).await;
    pool.map_err(Into::into)
}

//context.rs
use crate::db::TiberiusConnectionManager;
use bb8::Pool;

pub struct GraphQLContext {
    pub sn_mirror_connection: Pool<TiberiusConnectionManager>,
}


//main.rs
 let sn_mirror_connection = create_connection("psqlitsm", "sn_mirror")
        .await
        .expect("Failed to start sn_mirror");

    let schema = Schema::build(QueryRoot, MutationRoot, SubscriptionRoot)
        .data(GraphQLContext {
            sn_mirror_connection,
        })
        .finish();

//graphql.rs
   async fn find_cmdb_ci_service(&self, ctx: &Context<'_>, id: ID) -> FieldResult<CmdbCiService> {
        let conn = ctx.data::<GraphQLContext>()?.sn_mirror_connection.clone();
        let mut conn = conn.get().await?;
        graphql_translate(CmdbCiServices::find(&mut conn, id.as_str()).await)
    }
```

**Comment by servonlewis** [comment]
Do let me know if there are any mistakes! but it does work and fast after the first initial query.  think my auth is slow or something.

**Comment by pimeys** [comment]
Creating a connection is slow with many SQL databases, therefore reusing and pooling them is a good idea.

**Comment by servonlewis** [comment]
Would anyone happen to know how many connections my code above would have in its pool?  How do I know it's not just 1?

**Comment by pimeys** [comment]
You can define the maximum size with bb8's builder: https://docs.rs/bb8/0.7.0/bb8/struct.Builder.html#method.max_size

Usually how these pools work is they immediately open the minimum amount of connections, and only add more if needed, e.g. all the connections are in use and there's still some space to open more. Remember, your database connections are expensive and it's always better if you can model your code so that you need as few connections as possible still with a good throughput.

What this means is try to avoid long-running transactions, run your code close to the database so the roundtrip time is fast and model your database so with indices and normalizing, so that your queries are fast.

**Comment by servonlewis** [comment]
> You can define the maximum size with bb8's builder: https://docs.rs/bb8/0.7.0/bb8/struct.Builder.html#method.max_size
> 
> 
> 
> Usually how these pools work is they immediately open the minimum amount of connections, and only add more if needed, e.g. all the connections are in use and there's still some space to open more. Remember, your database connections are expensive and it's always better if you can model your code so that you need as few connections as possible still with a good throughput.
> 
> 
> 
> What this means is try to avoid long-running transactions, run your code close to the database so the roundtrip time is fast and model your database so with indices and normalizing, so that your queries are fast.

Thank you. I was reading the docs and it seems they have no default minimum connection number. 

I am thinking I should set it to 1 or 2 because it takes about 20 seconds to run the first query because of the handshake. Not sure why it takes so long to be honest. After the first query to that pool, it's extremely fast
