### ISSUE TITLE
no `TcpStream` in `net`

### ISSUE THREAD

**Issue by zirill** [prisma/tiberius#151]
Hello, please help with a starting example.

I tried an example from redme and from the example folder.
And I keep getting this error:

```
     | use tokio::net::TcpStream;
     |     ^^^^^^^^^^^^^^^^^^^^^ no `TcpStream` in `net`
```

Ubuntu 20.04
rustc 1.52.1

My cargo:
[dependencies]
tiberius = "0.5.13"
tokio = {version = "1.6", feature = ["full"]}
once_cell = "1.7.2"

[dependencies.tokio-util]
version = "0.6.7"
features = ["compat"]

**Comment by pimeys** [comment]
You have a typo. It should be:

```toml
 tokio = {version = "1.6", features = ["full"]}
```

So, `features`, not `feature`.
