### ISSUE TITLE
trivial README upgrade

### ISSUE THREAD

**Issue by yatesco** [prisma/tiberius#16]
Hi there, I realise this is trivial in the grand scheme of things, but your README contains: "Documentation (deprecared, compile from this branch)" which I _think_ is now redundant given that the old async branch is your new master branch?

If so, I'll submit a PR removing it

**Comment by pimeys** [comment]
Fixed them a bit. You still need to compile docs from the master branch. Whatever is in docs.rs doesn't reflect the current state anymore.
