### ISSUE TITLE
Protocol error: invalid or unsupported column type: 40

### ISSUE THREAD

**Issue by smuel-adm** [prisma/tiberius#164]
I've a table like this one:
```sql
CREATE TABLE TiberiusDate (
    ID int,
    Date date,
);
```

If I select entries like this

```rust
// usual tiberius setup as described in the README ...
let rows = client.query("SELECT [ID], [Date] FROM [DevTestDB].[dbo].[TiberiusDate]", &[])
    .await?
    .into_first_result()
    .await?;
```

I got this error:
```shell
Error: Protocol error: invalid or unsupported column type: 40
```

The Date Datatype is currently not supported. Are there any plans to add this type. I have to work with many databases that use that Date type ;(

**Comment by pimeys** [comment]
It is supported... You should enable the `chrono` feature to really use them though.

This works for me with latest tiberius:

```rust
#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let config = Config::from_ado_string(&CONN_STR)?;

    let tcp = TcpStream::connect(config.get_addr()).await?;
    tcp.set_nodelay(true)?;

    let mut client = Client::connect(config, tcp.compat_write()).await?;

    let rows = client
        .query("SELECT [ID], [Date] FROM [dbo].[TiberiusDate]", &[])
        .await?
        .into_first_result()
        .await?;

    println!("{:?}", rows);

    Ok(())
}
```

Outputs: `[Row { columns: [Column { name: "ID", column_type: Intn }, Column { name: "Date", column_type: Daten }], data: TokenRow { data: [I32(Some(1)), Date(Some(Date(737999)))] } }]`

**Comment by smuel-adm** [comment]
I missed the `default-features = false` in my Cargo.toml which had deactivated `tds73`.  🙈

Thank you for this fast answer.
