### ISSUE TITLE
Error forming TLS connection: unexpected EOF

### ISSUE THREAD

**Issue by lanklaas** [prisma/tiberius#172]
Hi,

When using tiberius in an alpine docker build I get the error in the description. I created a minimal case [here](https://github.com/lanklaas/tiberius-tls-test)

The readme explains how to run it.

When I run this code from my machine it works with the same database on the repo. My machine details:
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=21.04
DISTRIB_CODENAME=hirsute
DISTRIB_DESCRIPTION="Ubuntu 21.04"

The issue goes away when I turn off(NotSupported) encryption in the config.

On the alpine build libressl headers are installed and the openssl static variable is set to true. This way of static linking usually works with openssl-sys

Please let me know if you need more info

**Comment by pimeys** [comment]
Can you try with feature flag `vendored-openssl` if it still persists? SQL Server certificates are, well they are kind of special and it's also a known issue you can't really connect to the server from macOS, if you link to the Security Framework.

I'm happy to get some more debugging and maybe even a PR if you think it is Tiberius issue, not an issue where SQL Server has old and a bit too invalid certificate for LibreSSL to work.

We just statically link OpenSSL nowadays...

**Comment by pimeys** [comment]
And `vendored-openssl` uses whatever openssl version is delivered with the `openssl-sys` crate.

**Comment by lanklaas** [comment]
Ok thanks,

vendored-openssl fixes the issue in the minimal example, but it seems like it causes clashes in my actual code that also uses openssl.

The error (from hyper):

```
hyper::Error(Connect, ConnectError { error: Error { code: ErrorCode(1), cause: Some(Ssl(ErrorStack([Error { code: 337047686, library: "SSL routines", function: "tls_process_server_certificate", reason: "certificate verify failed", file: "ssl/statem/statem_clnt.c", line: 1913 }]))) }, verify_result: X509VerifyResult { code: 20, error: "unable to get local issuer certificate" } })
```

I will remove the lock files and try to build again. I will close this then as the issue is not with tiberius anymore.

Thanks
