### ISSUE TITLE
Replace native-tls with rustls

### ISSUE THREAD

**Issue by lostiniceland** [prisma/tiberius#176]
While using Tiberius and other libraries which require the native-tls crate and by extension openssl this creates a more complicated build environment due to the openssl c dependency. I recently struggled getting this to compile for OSX for instance which seem to facing out openssl completely.

Anyways, I was wondering if it would be feasible (and usefull) for tiberius to replace the native-tls dependency with rustls? There also exists a async wrapper [async-rustls](https://github.com/smol-rs/async-rustls).
Maybe this dependency could be switched with a feature-flag when using tiberius.

**Comment by esheppa** [comment]
Hi @lostiniceland, one option that is built into `tiberius` currently is using the `vendored-openssl` feature, which statically links against OpenSSL and is designed for use on macOS.

We have previously attempted to use `rustls` in `tiberius` as this would be preferable for static builds, however we were unable to get this working. (You can find the previous progress here: https://github.com/prisma/tiberius/pull/82)

**Comment by lostiniceland** [comment]
I am reusing this thread since the issue is related. I am currently trying to figure out how to use the `vendored-openssl` feature with a custom-cert mssql instance.

There seems to be only the option do trust any server certificate: is there also a way to add ca-certificate?
Also I couldnt find any api to setup mtls with a client-certificate either.

**Comment by pimeys** [comment]
Hardest thing for me to do this feature is to just have a server with custom cert for testing. Implementation-wise it is not super hard to do, but currently no you cannot use custom certs.

If you want to try a PR, I'm happy to review!

**Comment by lostiniceland** [comment]
Thanks for the update. I could provide at least my docker-image and cert-creation scripts. 
I will add a ticket and try my best :-)
