### ISSUE TITLE
stream.try_next().await? Connection reset by peer (os error 104)

### ISSUE THREAD

**Issue by fospring** [prisma/tiberius#177]
When I connect to the remote server,return error
```
Error: Io { kind: BrokenPipe, message: "An error occured during the attempt of performing I/O: Connection reset by peer (os error 104)" }
```
The block function calling stack is 
```
match Client::connect(config, tcp.compat_write()).await
--> connection.flush_done().await?;
--> let token = stream.try_next().await?;
```
But I can use `sqlcmd` to connect remote server

**Comment by pimeys** [comment]
So your client cannot form a connection. Did you get the hostname right? Are you using TLS? For our users we haven't had this issue before, so maybe create a repo somewhere that can reproduce this issue every time when you run the code, and we'll see if there's an issue.

**Comment by fospring** [comment]
![error104](https://user-images.githubusercontent.com/19633691/137490977-3eba70d0-3f5b-4d03-a95c-97744b5b3f89.jpeg)

**Comment by fospring** [comment]
> Connection reset by peer is typically not a client problem, but your server cuts the connection. I don't know what kind of setup you're using. Do you have TCP enabled in SQL Server? I always just use the Microsoft SQL Server docker image and that works just fine. Our CI here also tests against the Windows version of SQL Server 2019 with TCP enabled and our CI pipeline is green.
> 
> Maybe take a look into the setup I do in the CI:
> 
> https://github.com/prisma/tiberius/blob/master/.github/workflows/test.yml#L98-L191

OK，let me check TCP enable option. I connect success when use Microsoft SQL Server docker image.
