### ISSUE TITLE
Tokio connect example not working

### ISSUE THREAD

**Issue by rkuhn** [prisma/tiberius#182]
The documented approach of using `tokio::net::TcpStream::connect()` to create a `Client` results in:
```
the trait bound `tokio::net::TcpStream: futures::AsyncRead` is not satisfied
the trait `futures::AsyncRead` is not implemented for `tokio::net::TcpStream`rustcE0277
```
Looking at the dependencies, I can confirm that this cannot possibly work: neither does Tokio depend on futures-rs nor the other way around, so such a trait impl can’t exist. Since this crate seems to be used, I must be missing something obvious, but the docs don’t enlighten me. If someone explains my error I vow to open a documentation PR :-)

**Comment by pimeys** [comment]
You need to use their adapter to the standard traits, as is written in the example:

https://docs.rs/tiberius/0.6.5/tiberius/#connecting-with-tokio

Look at the usage of `compat_write()` and the trait `use tokio_util::compat::TokioAsyncWriteCompatExt;`.

**Comment by rkuhn** [comment]
D’oh, thanks! I was tripped up by https://docs.rs/tiberius/0.6.5/tiberius/struct.Client.html not containing this information — would you mind a PR that shows the relevant import?

**Comment by pimeys** [comment]
Making docs better is always a good thing. Please send a PR :)
