### ISSUE TITLE
Dynamic parameters?

### ISSUE THREAD

**Issue by lanklaas** [prisma/tiberius#195]
Hello,

I am trying to run a parameterized query, but I do not know the values at compile time. The compiler can't seem to figure out the types here. Could you point me in the right direction here please:

```rust
let pars = vec!["adsf".to_string(), "adsfjnsadf".to_string()];
let pars = pars.iter().map(|x| x.as_str()).collect::<Vec<&str>>();
let conf = tiberius::Config::from_jdbc_string(
    "jdbc:sqlserver://localhost:1433;databaseName=mydb;user=sa;password=123",
)
.unwrap();
let tcp = TcpStream::connect(conf.get_addr()).await.unwrap();
// We'll disable the Nagle algorithm. Buffering is handled
// internally with a `Sink`.
tcp.set_nodelay(true).unwrap();
let c = tcp.compat_write();

// Handling TLS, login and other details related to the SQL Server.
let connection = Client::connect(conf.clone(), c).await?;
connection
    .query(
        "select * from table where field = @P1 and field2 = @P2",
        pars.as_slice(),
    )
    .await
    .unwrap()
    .into_results()
    .await
    .unwrap();
```

The compiler gives this error:

```
error[E0308]: mismatched types
  --> src/lib.rs:66:59
   |
66 |                 .query(ENT_QRY_FLR.replace("$flr", &qry), pars.as_slice())
   |                                                           ^^^^^^^^^^^^^^^ expected trait object `dyn ToSql`, found `str`
   |
   = note: expected reference `&[&dyn ToSql]`
              found reference `&[&str]`

For more information about this error, try `rustc --explain E0308`.
error: could not compile `legoz-data` due to previous error

```
Seems like it sees `str` and not `&str`

My compiler version
```
~/g/f/r/l/src (master) [101]> rustc -V
rustc 1.58.1 (db9d1b20b 2022-01-20)
```

**Comment by pimeys** [comment]
There's a trick to tell the compiler your string slice is a trait object:

```rust
let params = vec!["foo".to_string];
let params: Vec<_> = params.iter().map(|s| s as &dyn ToSql).collect();
let stream = client.query("SELECT @P1", params.as_slice()).await?;
```

When I have time I need to check if I miss some crucial trait so the user doesn't need to do this for an existing vector.

**Comment by lanklaas** [comment]
Thanks, that works

**Comment by pimeys** [comment]
Hey @lanklaas, I created a branch iterating on a different way to query. This would not make you to allocate a new string just to make the compiler happy. Would you like to give it a spin, and if it feels better I could finish it up and cut a new release.

https://github.com/prisma/tiberius/pull/196

Read the code, docs and especially the tests on how to use it. Should be quite simple (hopefully).

**Comment by lanklaas** [comment]
Thanks, I will give it a go tomorrow and let you know

**Comment by codebling** [comment]
@lanklaas may I ask how you're using this? 
I am trying to switch to Tiberius under a DB abstraction that already exists in my code. The query function in the abstraction accepts dynamic parameters, as you do in example above, but Tiberius' `get` and `try_get` require type annotations. Since there are multiple types per column and a variable number of columns, I'm not even sure how to even expose these to the caller of the abstraction. Is that a problem you were able to solve?
