### ISSUE TITLE
Connect to MS SQL server with backslash in name

### ISSUE THREAD

**Issue by sgasse** [prisma/tiberius#210]
Hi! A client that we work with has a MS-SQL server available at an address that looks like this:

```
10.0.0.1\SOMENAME
```

Using python and `pyodbc`, we can connect when we specify the host as `10.0.0.1\\SOMENAME` (masking the backslash with another backslash). With `tiberius`, we were not able to connect yet. Combinations tried:
```rust
config.host("10.0.0.1\\SOMENAME");
config.host("10.0.0.1\SOMENAME");
config.host(r"10.0.0.1\SOMENAME");
```

The error is:
```
Error: could not resolve address `"10.0.0.1\\SOMENAME:1433"`

Caused by:
    failed to lookup address information: Name or service not known

```

Do you have any hint what else we could try?

**Comment by pimeys** [comment]
Did you check our test run what it does?

Here's the action: https://github.com/prisma/tiberius/blob/main/.github/workflows/test.yml#L77-L183=
And how we connect: https://github.com/prisma/tiberius/blob/main/tests/named-instance-tokio.rs

The action is interesting because it sets up the server too... I'm usually on Linux, and our users don't really use the SQL Browser that much. We do have tests that work, but that's the best I can give to you :)

**Comment by pimeys** [comment]
Oh, and don't set the instance in the host setup. There's a special method for that: https://docs.rs/tiberius/0.8.0/tiberius/struct.Config.html#method.instance_name

**Comment by sgasse** [comment]
I tried out both methods that you described. Building our own `Config` and setting the instance name via `config.instance_name(...)` did not work in our case. However the method with the ADO string as used in the CI worked :slightly_smiling_face: . Here is a minimal example in case someone else runs into it:

```rust
#[async_std::main]
async fn main() -> anyhow::Result<()> {
    let args = Args::parse();

    let ado_str = &format!(
        "server=tcp:{};uid={};pwd={};database={};TrustServerCertificate=true",
        args.host, args.user, args.password, args.database
    );
    println!("Using connection string: {}", ado_str);
    let config = Config::from_ado_string(ado_str).unwrap();

    let tcp = TcpStream::connect_named(&config).await?;
    tcp.set_nodelay(true)?;

    let mut client = Client::connect(config, tcp).await?;
    println!("Client connected");

    // Queries etc. following here
}
```

Thank you again for the help! :pray: I will close the issue.
