### ISSUE TITLE
config method chaining

### ISSUE THREAD

**Issue by paddymills** [prisma/tiberius#223]
It would be nice to be able to chain the methods for the `Config` struct.

Currently doing something like
```
let mut config = Config::new();
    config.host(HOST);
    config.authentication(AuthMethod::Integrated);
    config.trust_cert();
```

would be nice to do (similar to the `bb8::Pool::builder()` syntax)
```
let config = Config::new()
    .host(HOST)
    .authentication(AuthMethod::Integrated)
    .trust_cert();
```

I tried modifying these methods to return `&mut Self`, but found out that this causes issues with bb8_tiberius. I'm not sure if this a reasonable request for this library or if it doesn't fit well with the API design.

**Comment by pimeys** [comment]
They all got their downsides. Breaking the current API to annoy all users using Tiberius is not really top of my list currently...
