### ISSUE TITLE
Cannot query with a date between condition.

### ISSUE THREAD

**Issue by bgalvao** [prisma/tiberius#264]
I'm not sure if this is the right place to ask. I am using `connectorx` which uses this package.

I am trying to run a select query from python:

```sql
SELECT * FROM table
WHERE date_column
BETWEEN '2022-07-01' AND '2022-07-31'
```

I am using single-quotes on those dates.  This results in the error

```
[2022-12-15T13:35:40Z ERROR tiberius::tds::stream::token] Conversion failed when converting the varchar value '2022-07-01' to data type int. code=245
```

Is there a way to pass those dates in a way to make the query work with tiberius?

**Comment by fopsdev** [comment]
hi there,
maybe the Answer of:
https://stackoverflow.com/questions/65841023/sql-between-date-range-on-string-date
can help you.

**Comment by bgalvao** [comment]
nevermind this, it was definitely a mistake I was doing out of exhaustion - I was specifying a wrong column. Sorry to bother!
