### ISSUE TITLE
error: linking with `cc` failed: exit status: 1 - /usr/bin/ld: cannot find -lgssapi_krb5: No such file or directory

### ISSUE THREAD

**Issue by cirqueira-labs** [prisma/tiberius#273]
Hello guys. I'm trying to compile, but a got this error.
I have all the dependencies such libgssapi_krb5.so on /usr/lib64

**Comment by cirqueira-labs** [comment]
I removed the features 'all' and now it's working

**Comment by pimeys** [comment]
Yeah, you need the kerberos libraries if you want that support.
