### ISSUE TITLE
Possibility to use Tiberius with different runtimes

### ISSUE THREAD

**Issue by pimeys** [prisma/tiberius#29]
It would be great if we'd be able to use Tiberius with other runtimes than Tokio. This means no spawning, and it also means the underlying transportation protocol should be possible to inject into the connection. `TcpStream` and `TlsStream` must be able to be chosen by the user, as long as the streams implement `AsyncRead` and `AsyncWrite` from the futures crate. The Tokio counterparts can deal with the abstractions by using Tokio's compat module.

For making it easier for the user, we could provide separate crates:
- tiberius-tokio
- tiberius-async-std

Or additionally this can be handled with feature flags.

The other part needing replacement is the use of `tokio_codec`. [futures_codec](https://crates.io/crates/futures_codec) is a good replacement using the standard `AsyncRead` and `AsyncWrite`.

One should take into consideration of replacing the `bytes` crate while doing the refactoring, due to `bytes` being quite unsafe and triggering segmentation faults if using it wrong. One crate to experiment with is [byte_pool](https://docs.rs/byte-pool/0.2.1/byte_pool/), being a safe replacement for `bytes`. Be aware of writing the corresponding byte extensions to the `SqlReadBytes`.

**Comment by pimeys** [comment]
@esheppa should have some preliminary research and work done already for this.

**Comment by esheppa** [comment]
There are a few trade-offs either way, however the changes should be fairly targeted - so if we do choose one way, it shouldn't be too hard to change to the other.

If we go down the path of using a type parameter for the `TcpStream` then we probably need to provide multiple crates as mentioned. This style is used by `tokio-postgres` (partially, it provides a feature runtime, which can be turned off, and then the [`connect_raw`](https://github.com/sfackler/rust-postgres/blob/master/tokio-postgres/src/connect_raw.rs) function must be used and a stream from the user provided.

Positives:
* Anyone can implement support for another runtime without needing to fork the project

Negatives:
* Have to maintain the core crate plus one crate for each supported runtime (albeit these crates would be very minimal)
* The current state of implementation also depends on `async-trait` - this could potentially be removed but it would make implementation less ergonomic. However we could also change the trait into just a regular async function similar to how `tokio-postgres` handles this
* To do this properly requires another abstraction over the various versions of `ToSocketAddrs` as the current test implementation is simply using a `String`

If we use feature flags then there only needs to be a single crate and the user can specify which runtime they would like to use. This style is used by `SQLx` [here](https://github.com/launchbadge/sqlx/blob/master/sqlx-core/src/runtime.rs). They also use a compiler error to make runtime choice mutually exclusive. There is some good discussion [here](https://github.com/launchbadge/sqlx/issues/6).

Positives:
* Can use spawning when required (but this must be implemented for each runtime)

Negatives:
* For a new runtime to be supported it must either be a change in this crate, or the user would have to fork the crate to implement by themselves (however there is not currently a large number of runtimes)

Also:
* Smol runtime has recently been merged into `async-std` - however the `Async<std::net::TcpStream>` is wrapped by `async-std`'s so we would still need to maintain support for both `smol` and `async-std`
* It would be nice to add support for  [may](https://github.com/Xudong-Huang/may) also.

Current Thoughts
* I'm going to rewrite the test implementation using feature flags as it seems that they have less downsides for now - it also seems that there is not such a large number of runtimes so the maintenance overhead shouldn't be too large. This may also make it easier to do #28 as there would be access to spawning.
* While doing the above I'll investigate replacing `bytes` with `byte_pool` or equivalent
* Currently using `async-native-tls` which works nicely across multiple runtimes
* Might also add in `async-tls` to allow use of `rustls`

**Comment by pimeys** [comment]
I'm fine with the feature flag approach. Maybe the tcp stuff can be boxed in this case, so the user don't need to deal with type parameters, especially when the parameters are different depending on the feature flags.

Or, would it even be possible to do something like:
```rust
#[cfg(feature = "async-std")]
stream: async_std::TcpSTream,
#[cfg(feature = "tokio")]
stream: tokio::TcpStream,
```
Would the crates be similar enough we could work this out without using traits? Otherwise I see a solution that goes
```rust
stream: Box<dyn TcpStreamish>,
```
instead of having the trait as a type parameter for the `Client` (`Connection` doesn't really matter due to it being an internal type).

**Comment by pimeys** [comment]
Stjepan [thinks](https://twitter.com/stjepang/status/1241028963033657344) it's better to inject the stream to the crate and have separate crates for tokio and async-std.

**Comment by pimeys** [comment]
Thank you @esheppa for implementing this!
