### ISSUE TITLE
rust-encoding is unmaintained

### ISSUE THREAD

**Issue by eitsupi** [prisma/tiberius#292]
See lifthrasiir/rust-encoding#127

https://github.com/prisma/tiberius/blob/4bf88bf9aacb0b10c2847589ebb0262d98115e22/Cargo.toml#L43

**Comment by tomhoule** [comment]
Thanks for raising that. Are you aware of a maintained, popular alternative?

**Comment by eitsupi** [comment]
Thank you for your immediate reply.
Looking at the linked issue, it appears that some projects are moving to https://github.com/hsivonen/encoding_rs.

OSSystems/compress-tools-rs#112
crate-ci/typos#703

**Comment by suzak** [comment]
I created a PR for fixing this issue a month ago.

- #285

**Comment by tomhoule** [comment]
Closed by @suzak 's PR, indeed https://github.com/prisma/tiberius/pull/285

**Comment by max-sixty** [comment]
Would it be possible to make a release with this change?
