### ISSUE TITLE
`connection-string`  has deprecated rust code

### ISSUE THREAD

**Issue by max-sixty** [prisma/tiberius#295]
FYI in PRQL we get this for our builds:

```
 1  warning: the following packages contain code that will be rejected by a future version of Rust: connection-string v0.1.13
 note: to see what the problems were, use the option `--future-incompat-report`, or run `cargo report future-incompatibilities --id 17`
```

...which I think is from Tiberius...

```
 cargo tree -i connection-string
connection-string v0.1.13
└── tiberius v0.12.1
    [dev-dependencies]
    └── prql-compiler v0.8.1 (/Users/maximilian/workspace/prql/prql-compiler)
```

FYI it does look like there are newer versions available: https://crates.io/crates/connection-string/versions

(I'm triaging atm so won't make the PR myself, hope it's still helpful to put the issue in...)

**Comment by janpio** [comment]
0.12.2 of tiberius upgraded connection-string to 0.2 - so maybe that is already enough?

**Comment by max-sixty** [comment]
My apologies @janpio ! I should have checked whether we'd upgraded. Thank you.
