### ISSUE TITLE
future cannot be sent between threads safely

### ISSUE THREAD

**Issue by bbigras** [prisma/tiberius#43]
I had problems with the "old tiberius" when I tried to use it with async web frameworks like actix or warp. I ended up having to run the tiberius stuff with something like `tokio::task::spawn_local` and use channels to connect the web part with the tiberius part. Which was a pain.

Maybe I'm not doing something correctly or maybe using something like deadpool could help.

```toml
[dependencies]
futures = "0.3.5"
tiberius = "0.4.0-alpha.6"
tokio = { version = "0.2", features = [ "process", "rt-util", "macros", "rt-core" ] }
```

```rust
use futures::stream::StreamExt;
use futures::stream::TryStreamExt;
use tiberius::{AuthMethod, Client};

async fn something(mut conn: Client) -> Vec<i8> {
    let mut stream = conn
        .query("SELECT @P1 AS first; SELECT @P2 AS second", &[&1i32, &2i32])
        .await
        .unwrap();

    let first_result: Vec<Option<i32>> = stream
        .by_ref()
        .map_ok(|x| x.get::<i32, _>(0))
        .try_collect()
        .await
        .unwrap();

    assert!(stream.next_resultset());

    Vec::new()
}

#[tokio::main]
async fn main() {
    let mut builder = Client::builder();
    builder.host("localhost");
    builder.port(1433);
    builder.database("master");
    builder.authentication(AuthMethod::sql_server("SA", "<YourStrong@Passw0rd>"));
    builder.trust_cert();

    let mut conn = builder.build().await.unwrap();

    let f = something(conn);

    tokio::spawn(f);
}
```

```
error: future cannot be sent between threads safely
   --> src/main.rs:36:5
    |
36  |     tokio::spawn(f);
    |     ^^^^^^^^^^^^ future returned by `something` is not `Send`
    |
   ::: /home/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/task/spawn.rs:127:21
    |
127 |         T: Future + Send + 'static,
    |                     ---- required by this bound in `tokio::task::spawn::spawn`
    |
    = help: the trait `std::marker::Sync` is not implemented for `dyn tiberius::to_sql::ToSql`
note: future is not `Send` as this value is used across an await
   --> src/main.rs:6:22
    |
6   |       let mut stream = conn
    |  ______________________^
7   | |         .query("SELECT @P1 AS first; SELECT @P2 AS second", &[&1i32, &2i32])
    | |                                                               ----- has type `&dyn tiberius::to_sql::ToSql` which is not `Send`
8   | |         .await
    | |______________^ await occurs here, with `&1i32` maybe used later
9   |           .unwrap();
    |                    - `&1i32` is later dropped here

error: future cannot be sent between threads safely
   --> src/main.rs:36:5
    |
36  |     tokio::spawn(f);
    |     ^^^^^^^^^^^^ future returned by `something` is not `Send`
    |
   ::: /home/bbigras/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/task/spawn.rs:127:21

    |
127 |         T: Future + Send + 'static,
    |                     ---- required by this bound in `tokio::task::spawn::spawn`
    |
    = help: the trait `std::marker::Send` is not implemented for `dyn futures_core::stream::Stream<Item = std::result::Result<tiberius::tds::stream::token::ReceivedToken, tiberius::error::Error>>`
note: future is not `Send` as this value is used across an await
   --> src/main.rs:11:42
    |
6   |       let mut stream = conn
    |           ---------- has type `tiberius::result::QueryResult<'_>` which is not `Send`
...
11  |       let first_result: Vec<Option<i32>> = stream
    |  __________________________________________^
12  | |         .by_ref()
13  | |         .map_ok(|x| x.get::<i32, _>(0))
14  | |         .try_collect()
15  | |         .await
    | |______________^ await occurs here, with `mut stream` maybe used later
...
21  |   }
    |   - `mut stream` is later dropped here
```

**Comment by pimeys** [comment]
The old version took the ownership of a connection to the future, which is kind of not nice if something breaks while holding the ownership and the connection is lost.

Why don't you try to model the code a bit differently. For example using a connection pool in an `Arc`, cloning it to the spawn and only inside the spawn getting a new connection out of the pool.

Some good and easy pools to try:
- https://crates.io/crates/deadpool
- https://crates.io/crates/mobc

It is MUCH nicer to be able to take the connection as a reference when querying. And it is quite easy to get around the `Send` restrictions by using a pool and `Arc`.

P.S. sorry for slow response, been quite a hectic week with Tiberius. Tomorrow stable 0.4.0 is going to be out though!

**Comment by bbigras** [comment]
Since deadpool's Pool already use an arc, I can just clone it right?

```rust
pub struct Pool<T, E> {
    inner: Arc<PoolInner<T, E>>,
}
```

> It is MUCH nicer to be able to take the connection as a reference when querying. And it is quite easy to get around the Send restrictions by using a pool and Arc.

If I have a transaction, can I pass it to some async functions?

Like if I want to do something like this but with a transaction. That's useful if I need to do a query for each result of a first query:

```rust
    let mut client = pool.get().await.unwrap();

    let mut stream = client.query("SELECT @P1", &[&1i32]).await?;

    let first_result: Vec<Option<i32>> = stream
        .by_ref()
        .map_ok(|x| x.get::<i32, _>(0))
        .try_collect()
        .await?;

    stream.next_resultset();

    for i in 0..2 {
        something(&stream).await;
    }
```

```
96  |         something(&stream).await;
    |         ^^^^^^^^^^-------^^^^^^^- `&stream` is later dropped here
    |         |         |
    |         |         has type `&tiberius::result::QueryResult<'_>` which is not `Send`
    |         await occurs here, with `&stream` maybe used later
```

> P.S. sorry for slow response, been quite a hectic week with Tiberius. Tomorrow stable 0.4.0 is going to be out though!

No worries. Thanks for your time :)

**Comment by pimeys** [comment]
Yep. You can just clone the `Pool` quite cheaply.

For the second example, could you just transfer all results to memory first and then call `something` with the owned results?

**Comment by pimeys** [comment]
For high level transaction support please comment to this issue. https://github.com/prisma/tiberius/issues/28

**Comment by bbigras** [comment]
> For the second example, could you just transfer all results to memory first and then call something with the owned results?

Yep.

`stream` can't be passed to `something()` right? And it's no big deal since I'm not using a transaction and if I did, that would be a problem addressed by #28.

**Comment by pimeys** [comment]
At least the `QueryResult` implements `Send`, so if you don't have also the `Sync` boundary you can pass it to a function by-value. Seems like in your case a reference to a `QueryResult` is not `Send`, that's why the example doesn't work.

**Comment by bbigras** [comment]
Oh so I can do:

```rust
for i in 0..2 {
    stream = something(stream).await?;
}
```

Thank you very much.

and thank you so much to you (and possibly other collaborators) for not letting this crate die.
