### ISSUE TITLE
Chrono structs doesn't work with default-features disabled

### ISSUE THREAD

**Issue by madmaxio** [prisma/tiberius#45]
When using like this 
tiberius = { git = "https://github.com/prisma/tiberius",  default-features = false, features = ["chrono"] }
there is
the trait `tiberius::from_sql::FromSql<'_>` is not implemented for `chrono::naive::datetime::NaiveDateTime

While same code works for
tiberius = { git = "https://github.com/prisma/tiberius"}

**Comment by pimeys** [comment]
Yikes. I'll take a look tomorrow.

**Comment by pimeys** [comment]
Ah. Hey. Could you try with features `["chrono", "tds73"]`? Or are you bound to an old version of SQL Server (2005) that doesn't support `tds73`. It should work though without `tds73` feature from `datetime` columns, so I should take a look.

**Comment by madmaxio** [comment]
Worked with tds73.
