### ISSUE TITLE
How to read and write int？

### ISSUE THREAD

**Issue by songlinshu** [prisma/tiberius#59]
Hello， How to read and write MSSQL int ?

**Comment by pimeys** [comment]
`int` is `i32` in Rust, so take a look how the [test](https://github.com/prisma/tiberius/blob/master/tests/query.rs#L417-L432) does it.

This probably needs some documentation I see, but you can read other mappings from the [`column_data.rs`](https://github.com/prisma/tiberius/blob/master/src/tds/codec/column_data.rs#L66-L102).

**Comment by pimeys** [comment]
Documented in https://github.com/prisma/tiberius/pull/60
