### ISSUE TITLE
Connecting to Azure SQL with tokio (on mac) gives a Tls connection closed via error.

### ISSUE THREAD

**Issue by AdsSengupta** [prisma/tiberius#65]
this is my code

```rust
let mut config = Config::from_ado_string("server=xxx.database.windows.net,1433;UID=xxx;PWD=xxx;TrustServerCertificate=true")?;
let tcp = TcpStream::connect(config.get_addr()).await?;
tcp.set_nodelay(true)?;
let mut client = Client::connect(config, tcp.compat_write()).await.expect("Failed!");
```
and I get
```thread 'main' panicked at 'Failed!: Tls("connection closed via error")', src/main.rs:80:22```

**Comment by AdsSengupta** [comment]
It works without issues on Windows

**Comment by pimeys** [comment]
What version? I remember @esheppa fixing this a while ago already.

**Comment by parkerp1** [comment]
@pimeys  Has there been a solution to this? I am currently running into this issue for my own project

**Comment by AdsSengupta** [comment]
I ended up using ODBC since it doesn't work on the latest release.

**Comment by AdsSengupta** [comment]
I believe it's a mac TLS issue since it works on Linux

**Comment by pimeys** [comment]
We might need a developer using a Mac to fix this issue...

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by parkerp1** [comment]
@AdsSengupta I ended up using ODBC as well

**Comment by pimeys** [comment]
It seems to be a problem with native-tls and Catalina:

https://github.com/sfackler/rust-native-tls/issues/151

**Comment by pimeys** [comment]
It would be really nice if somebody could debug this a bit, forking Tiberius and then in their app then pointing to this fork and seeing certain things first:

- See if it fails with Tokio and async-std both
- If async-std works, maybe trying to patch `async-native-tls` in `Cargo.toml` with
```toml
async-native-tls = { version = "0.4", default-features = false, features = [ "runtime-tokio" ] }
```

If none of these work, the problem might be with the system certificates (Catalina has more strict rules how big the certificate needs to be compared to the older mac versions).

**Comment by pimeys** [comment]
Here's a ticket that might provide some useful information:

https://github.com/microsoft/azuredatastudio/issues/6949

**Comment by pimeys** [comment]
And another one:

https://github.com/microsoft/mssql-docker/issues/37

**Comment by pimeys** [comment]
I found a way to get TLS working on macOS and here's the plan how to move forward:

We create a new crate async-openssl that takes some code from native-tls and async-native-tls. This crate uses openssl always, and we can force vendoring to statically compile openssl.

From here Tiberius would have a new feature flag `force-openssl` that then uses this new crate instead of async-native-tls, and vendors openssl to the binary. I tried this approach by modifying native-tls to always use openssl and it definitely seems to fix connection issues on macOS.

Candidating for the next release.

**Comment by pimeys** [comment]
Hey all! TLS should now work on macOS systems. With no additional feature flags you must have OpenSSL installed to your system before compiling Tiberius. You can also use a feature flag `vendored-openssl` to use the vendored version from crates.io, which links to it statically. This is probably not the best thing security-wise, but if you're not running a macOS server, only using it for development, why not?

Please open up a new issue if having problems.

**Comment by pimeys** [comment]
Versions 0.5.2 and 0.4.19 are released with this fix.

**Comment by esheppa** [comment]
@schneipp - Because the default features block has `default = ["tds73", "winauth", "native-tls"]` you'll need to set `default-features = false` and then explicitly set `tds73` along with your desired TLS implementation. 

@pimeys this would be fixed by https://github.com/prisma/tiberius/pull/237

**Comment by schneipp** [comment]
OH! Damn it - i'm so sorry! I had tiberius in my shared types folder for some macro magic where i didn't set the correct feature flags. 
Everything works now as expected. Thank you!
