### ISSUE TITLE
Query result is not read from stored proc

### ISSUE THREAD

**Issue by SpeedSX** [prisma/tiberius#66]
My stored procedure looks like this:
```sql
CREATE PROCEDURE [dbo].[sp_NewItem] 
  @Param1 varchar(20),
  @Param2 datetime
AS
  insert into Items (Param1, Param2)
  values (@Param1, @Param2)

  return SCOPE_IDENTITY()
```
The code which calls that stored procedure is
```rust
        let result = client.query(
                "declare @rc int; exec @rc = sp_NewItem @P1, @P2; select @rc as Id", 
                &[&param1, &param2])
            .await?
            .into_row()
            .await?;
```
and the result set is empty.
The workaround I found is using 'nocount' outside a procedure call. Like this:
````
"set nocount on; declare @rc int; exec @rc = sp_NewItem @P1, @P2; select @rc as Id", 
````
So it seems that it reads number of affected rows from stream and stops. I also tried to update SP to use 'select' instead of 'return', but that doesn't change much. 
This proc is an old legacy database, but I've never had this problem before, working with other drivers. 
What do you think, is that a bug?

**Comment by esheppa** [comment]
Hi @SpeedSX - I've tried this out locally and this does seem to be a bug - as you've guessed once it reads a "rows affected" amount, it ends the result set. I'll shortly put up a pull request which fixes this.
