### ISSUE TITLE
Executing more than 254 queries on a single connection panics with "attempt to add with overflow"

### ISSUE THREAD

**Issue by mlcruz** [prisma/tiberius#68]
### Repro:
```

#[test]
fn repro() {
    use smol::Async;
    use std::net::TcpStream;
    use tiberius::{Client, Config};

    smol::run(async {
        let conn_config = Config::from_ado_string(TEST_MSSQL_CONN_STR).unwrap();

        let stream = Async::<TcpStream>::connect(conn_config.get_addr())
            .await
            .unwrap();

        let mut connection = Client::connect(conn_config, stream).await.unwrap();

        for i in 1..255 {
            println!("OK - {}", i);
            connection.simple_query("SELECT 1").await.unwrap();
        }
    });
}
```

### Result: 
- thread  panicked at 'attempt to add with overflow, src\tds\context.rs:31:9 (after 254 iterations)

### Cause:
The issue happens due to id in the next_packet_id method being u8 and overflowing:

#src\tds\context.rs:29-34:
```
 pub fn next_packet_id(&mut self) -> u8 {
        let id = self.packet_id; 
        self.packet_id += 1;
        id
    }
```

This one appears to be pretty straightforward to fix. I could have submitted a PR fixing it, but i'm not that familiar with the library yet to go around possibly breaking stuff.

Also, thanks for the great work bringing this project back to life.

**Comment by esheppa** [comment]
Hi @mlcruz - did you run the test on debug or release mode? This should only occur on debug mode as on release mode the addition will wrap around.

as per the spec, the packet_id has to be a `u8`
> 2.2.3.1.5 PacketID
PacketID is used for numbering message packets that contain data in addition to the packet header.
PacketID is a 1-byte, unsigned char. Each time packet data is sent, the value of PacketID is
incremented by 1, modulo 256.<7> This allows the receiver to track the sequence of TDS packets for
a given message. This value is currently ignored.

However I've submitted a PR to make the wrapping explicit which would avoid this panic on debug mode

**Comment by mlcruz** [comment]
Hello @esheppa. 

You are correct, this is only an issue in debug mode.  

Thanks for submitting a PR fixing it and for the comprehensive response.
