### ISSUE TITLE
panicked at 'skipping env change type Routing'

### ISSUE THREAD

**Issue by Niedzwiedzw** [prisma/tiberius#83]
https://github.com/prisma/tiberius/blob/d90462dfa5cafaf32e8c1815aee3bf7c28bdb5e4/src/tds/codec/token/token_env_change.rs#L167

same code yields correct results on windows, whilst crushing when compiled and ran on a windows machine

**Comment by Niedzwiedzw** [comment]
@pimeys  looks like your discord invite link is expired, I wanted to join but it says the link is invalid

**Comment by pimeys** [comment]
https://discord.gg/xX4xp9x

**Comment by pimeys** [comment]
We don't handle the `Routing` event yet. We should maybe do something with it. Even skipping it is doing something if that's all we want right now. I'd appreciate a pull request, kind of busy right now :)

**Comment by pimeys** [comment]
We should handle this in the following way:

- parse the Routing token
- on the connection phase, if getting this token, result an error that gives the new address
- when user gets this error, they should create a new `TcpStream` to the given address and reconnect with Tiberius

**Comment by pimeys** [comment]
@Niedzwiedzw could you check if the pull request fixes the issue?

**Comment by Niedzwiedzw** [comment]
![image](https://user-images.githubusercontent.com/22037927/94670938-7f4dd000-0313-11eb-8c2a-37717f9b9c70.png)
just for future users, changing `connection policy` for mssql on azure panel `default` -> `proxy` removes this. If you don't care about distributedness, just change that one and you're good to go, no reconnects needed
