### ISSUE TITLE
Connection pool

### ISSUE THREAD

**Issue by pbartyik** [prisma/tiberius#85]
Is there a possibility with tiberius to maintain a pool of connections to the database, rather than firing up new connections every time need to make a query or use one connection for all queries?

[Someone](https://www.reddit.com/r/rust/comments/a71u5o/help_needed_in_writing_a_database_connection_ool) attempted to create one with r2d2 but it didn't work out.

**Comment by SpeedSX** [comment]
I created that using bb8 in my project, simple enough, but looks working. You can have a look at the source [here](https://github.com/SpeedSX/consum-api/blob/master/src/connection_manager.rs)

**Comment by pimeys** [comment]
Tiberius does not implement any pool, but it's quite straightforward to do one with [deadpool](https://crates.io/crates/deadpool) or [mobc](https://crates.io/crates/mobc).

**Comment by pimeys** [comment]
Also: r2d2 is a sync pool and you need an async pool. bb8/deadpool/mobc should all work quite easily.

**Comment by pbartyik** [comment]
Thanks! I'll be able to dig in a bit tomorrow.

**Comment by pimeys** [comment]
If you have trouble, you can join our discord and ask for help too.

**Comment by pimeys** [comment]
Also, just writing it down here:

We're not planning on adding a pool to Tiberius. We want to keep this as simple as possible async TDS implementation, letting other crates implement pooling, connection handling and all that. This is to make tiberius a) a small surface for bugs and b) it to be compatible with wide amount of different systems.

For now you should just handle the pooling by yourself with whatever crate you want to use. If needing some more integrated experience, with a bit of work to enable more types SQLx might give a better experience.

**Comment by aanavaneeth** [comment]
Hello @pimeys It will be nice if examples are provided with  deadpool or mobc. It will be helpful for beginners who like to explore connection pool.
