### ISSUE TITLE
On Handling Redirects

### ISSUE THREAD

**Issue by pimeys** [prisma/tiberius#88]
![firewall](https://user-images.githubusercontent.com/34967/94687591-fe470680-031b-11eb-9869-77fdd3aea44e.png)

Currently we are able to connect to Azure SQL with the firewall settings pictured above. If the connection policy is set to redirect, we'll error out with `Routing`, giving a new host and port. Although connecting to this new host gives an error how server name cannot be determined. If the original server was `foobar.database.windows.net`, the user was naturally `user@foobar`. But, if the redirect goes to `f02f9939c13c.tr2996.northeurope1-a.worker.database.windows.net`, the original username doesn't work anymore. We can try `user@f02f9939c13c.tr2996.northeurope1-a.worker`, `user@f02f9939c13c.tr2996.northeurope1-a`, `user@f02f9939c13c.tr2996` or `user@f02f9939c13c`, but all of these will give the same error.

I'm leaving this for now as an issue, if anybody else hits the same problem and finds some nice solution. For now, the only workaround is to set the connection policy to `proxy`.

**Comment by CJStadler** [comment]
I ran into this as well and investigated a bit. I noticed that the `LoginMessage` struct includes a `server_name` field, but it is always empty, which seems suspicious: https://github.com/prisma/tiberius/blob/904697180e008c93f1987104fd7b1f9d23babd35/src/tds/codec/login.rs#L148

I tried setting this to the server name (`foobar` in the above example) but just got a different error: `Token error: 'Database 'my_db_name' on server '' is not currently available`. It seems like the server name is still not registering. So I'm not sure if this is progress or I just made it worse.

I haven't been able to find documentation on what the expected format of the login message is — does any exist? Thanks!

**Comment by pimeys** [comment]
Hi @CJStadler and sorry for late response.

I haven't really found any good documentation, but if you'd like to debug a bit, I think the JDBC driver should have good enough code to see how it's handled in there.

https://github.com/microsoft/mssql-jdbc/blob/dev/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java#L2382

I went through it a while ago, but couldn't find how they do things differently.

Also we really can't reconnect automatically in Tiberius due to its architecture, but if we find the right way to reconnect, it should be quite trivial to do in the client code.

**Comment by pimeys** [comment]
This is now solved. The login packet needs the server name.
