### ISSUE TITLE
Public Errors

### ISSUE THREAD

**Issue by Spirans** [prisma/tiberius#93]
Hi!

I'm really impressed about tiberius (since it looks like the only really working mssql library - sqlx still doesn't support chrono date types, odbc not working, at least in my hands). So thank you very much for your work.

But for now, I'm trying to do some conversions from your `tiberius::Error` to mine, and I can't, because `tiberius::Error` is public only for its own crate. So I would be glad to understand the motivation behind this decision, or maybe I'm doing something entirely wrong and you would help me to find the right way to do so.

**Comment by esheppa** [comment]
Hi @Spirans, thanks for the question! In this case the `Error` re-export at the top level is `pub(crate)`, however it can be used via the `error` module ([`tiberius::error::Error`](https://docs.rs/tiberius/0.4.11/tiberius/error/enum.Error.html)), and it is declared as `pub enum` so the variants will be accessible.

**Comment by Spirans** [comment]
@esheppa thank you, it's really solving my problem!
