### ISSUE TITLE
`Config::from_jdbc_string` does not parse `databaseName`

### ISSUE THREAD

**Issue by guskovd** [prisma/tiberius#99]
for example:

```rust
#[async_std::main]
async fn main() -> anyhow::Result<()> {
    let jdbc = "jdbc:sqlserver://127.0.0.1;databaseName=rezerv;TrustServerCertificate=true";
    let config = Config::from_jdbc_string(jdbc)?;
    println!("{:?}", config);
    Ok(())
}
```

```bash
$ cargo run --example jdbc_parse
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/examples/jdbc_parse`
Config { host: Some("127.0.0.1"), port: None, database: None, instance_name: None, encryption: NotSupported, trust_cert: true, auth: SqlServer(SqlServerAuth { user: "", password: "<HIDDEN>"

**Comment by guskovd** [comment]
In the `microsoft` [documentation](https://docs.microsoft.com/en-us/sql/connect/jdbc/building-the-connection-url?view=sql-server-ver15) I only found` databaseName` (but not `database`)

**Comment by yoshuawuyts** [comment]
Hi @guskovd; thanks for filing this! I think you're right, and we should support `databaseName`. I'm less sure if we should _not_support `database`; I think @pimeys is in a better position to answer that.

Looking at the code the error seems to come from how we implement `ConfigString::database`: https://github.com/prisma/tiberius/blob/0aa66dce18b3ccc0d67c79b890353e2e60965c28/src/client/config.rs#L239-L244

One fix could be to override the default impl of `ConfigString::database` for JDBC: https://github.com/prisma/tiberius/blob/0aa66dce18b3ccc0d67c79b890353e2e60965c28/src/client/config/jdbc.rs#L19-L33

But if there are more differences in conventions between `ado.net` and `jdbc` we may have to ask ourselves whether it even makes sense to share a trait. But that seems like a much larger question which I don't know the answer to.

**Comment by pimeys** [comment]
Azure SQL gives us:

```
jdbc:sqlserver://my.database.windows.net:1433;database=prisma;user=x;password={y};encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
```

So here we have the `database`. Also I've seen `Initial Catalog` in use, so the current implementation for both (ado, jdbc) is:

https://github.com/prisma/tiberius/blob/master/src/client/config.rs#L239-L244

I would appreciate a pull request here to add a third option `databaseName`, updating the documentation accordingly.
